# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(236, 171)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 134))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.line_account = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_account.setObjectName("line_account")
        self.horizontalLayout_3.addWidget(self.line_account)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.line_passwd = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_passwd.setObjectName("line_passwd")
        self.horizontalLayout_4.addWidget(self.line_passwd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_auto = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_auto.setObjectName("checkBox_auto")
        self.horizontalLayout_2.addWidget(self.checkBox_auto)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.checkBox_member = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_member.setObjectName("checkBox_member")
        self.horizontalLayout_2.addWidget(self.checkBox_member)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_assign = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_assign.setObjectName("pushButton_assign")
        self.horizontalLayout.addWidget(self.pushButton_assign)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_align = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_align.setObjectName("pushButton_align")
        self.horizontalLayout.addWidget(self.pushButton_align)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_cancle = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cancle.setObjectName("pushButton_cancle")
        self.horizontalLayout.addWidget(self.pushButton_cancle)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.label_status = QtWidgets.QLabel(Form)
        self.label_status.setGeometry(QtCore.QRect(10, 160, 41, 9))
        self.label_status.setObjectName("label_status")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "          Cqupt WeChat"))
        self.label_2.setText(_translate("Form", "账户     "))
        self.line_account.setPlaceholderText(_translate("Form", "请输入你的账号"))
        self.label_3.setText(_translate("Form", "密码     "))
        self.line_passwd.setPlaceholderText(_translate("Form", "请输入你的密码"))
        self.checkBox_auto.setText(_translate("Form", "自动登录"))
        self.checkBox_member.setText(_translate("Form", "保存密码"))
        self.pushButton_assign.setText(_translate("Form", "登录"))
        self.pushButton_align.setText(_translate("Form", "注册"))
        self.pushButton_cancle.setText(_translate("Form", "取消"))
        self.label_status.setText(_translate("Form", "欢迎"))

