# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(536, 356)
        self.frame_friends = QtWidgets.QFrame(Form)
        self.frame_friends.setGeometry(QtCore.QRect(0, 0, 105, 361))
        self.frame_friends.setMinimumSize(QtCore.QSize(91, 361))
        self.frame_friends.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_friends.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_friends.setObjectName("frame_friends")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_friends)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_friends = QtWidgets.QScrollArea(self.frame_friends)
        self.scrollArea_friends.setMinimumSize(QtCore.QSize(91, 38))
        self.scrollArea_friends.setMaximumSize(QtCore.QSize(91, 361))
        self.scrollArea_friends.setWidgetResizable(False)
        self.scrollArea_friends.setObjectName("scrollArea_friends")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 70, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_zhangsan = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_zhangsan.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_zhangsan.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_zhangsan.setObjectName("pushButton_zhangsan")
        self.verticalLayout_3.addWidget(self.pushButton_zhangsan)
        self.pushButton_lisi = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_lisi.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_lisi.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_lisi.setObjectName("pushButton_lisi")
        self.verticalLayout_3.addWidget(self.pushButton_lisi)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_3.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_11.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_11.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_10.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_10.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_7.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_8.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_5.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_6.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_9.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_4.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.scrollArea_friends.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea_friends)
        self.frame_ChatInterface = QtWidgets.QFrame(Form)
        self.frame_ChatInterface.setGeometry(QtCore.QRect(100, 0, 331, 231))
        self.frame_ChatInterface.setMinimumSize(QtCore.QSize(311, 191))
        self.frame_ChatInterface.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ChatInterface.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ChatInterface.setObjectName("frame_ChatInterface")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_ChatInterface)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit_chat = QtWidgets.QTextEdit(self.frame_ChatInterface)
        self.textEdit_chat.setReadOnly(True)
        self.textEdit_chat.setObjectName("textEdit_chat")
        self.verticalLayout_2.addWidget(self.textEdit_chat)
        self.line = QtWidgets.QFrame(self.frame_ChatInterface)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.frame_SendMessageInterface = QtWidgets.QFrame(Form)
        self.frame_SendMessageInterface.setGeometry(QtCore.QRect(100, 220, 331, 140))
        self.frame_SendMessageInterface.setMinimumSize(QtCore.QSize(331, 140))
        self.frame_SendMessageInterface.setMaximumSize(QtCore.QSize(331, 131))
        self.frame_SendMessageInterface.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SendMessageInterface.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SendMessageInterface.setObjectName("frame_SendMessageInterface")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_SendMessageInterface)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_SendMessageInterface = QtWidgets.QTextEdit(self.frame_SendMessageInterface)
        self.textEdit_SendMessageInterface.setMinimumSize(QtCore.QSize(311, 90))
        self.textEdit_SendMessageInterface.setStyleSheet("\n"
"font: 13pt \"Arial\";")
        self.textEdit_SendMessageInterface.setObjectName("textEdit_SendMessageInterface")
        self.gridLayout.addWidget(self.textEdit_SendMessageInterface, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(254, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_SendMessageInterface = QtWidgets.QPushButton(self.frame_SendMessageInterface)
        self.pushButton_SendMessageInterface.setObjectName("pushButton_SendMessageInterface")
        self.gridLayout.addWidget(self.pushButton_SendMessageInterface, 1, 1, 1, 1)
        self.frame_groups = QtWidgets.QFrame(Form)
        self.frame_groups.setGeometry(QtCore.QRect(430, 0, 105, 361))
        self.frame_groups.setMinimumSize(QtCore.QSize(91, 361))
        self.frame_groups.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_groups.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_groups.setObjectName("frame_groups")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_groups)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_groups = QtWidgets.QScrollArea(self.frame_groups)
        self.scrollArea_groups.setMinimumSize(QtCore.QSize(91, 38))
        self.scrollArea_groups.setMaximumSize(QtCore.QSize(91, 361))
        self.scrollArea_groups.setWidgetResizable(False)
        self.scrollArea_groups.setObjectName("scrollArea_groups")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 70, 1000))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_addgroup = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_addgroup.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_addgroup.setObjectName("pushButton_addgroup")
        self.verticalLayout_5.addWidget(self.pushButton_addgroup)
        self.pushButton_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_12.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_12.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_5.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_13.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_13.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_5.addWidget(self.pushButton_13)
        self.pushButton_30 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_30.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_30.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_5.addWidget(self.pushButton_30)
        self.pushButton_31 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_31.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_31.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_31.setObjectName("pushButton_31")
        self.verticalLayout_5.addWidget(self.pushButton_31)
        self.pushButton_29 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_29.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_29.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout_5.addWidget(self.pushButton_29)
        self.pushButton_28 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_28.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_28.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_5.addWidget(self.pushButton_28)
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_14.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_14.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_5.addWidget(self.pushButton_14)
        self.pushButton_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_16.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_16.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_5.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_17.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_17.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_5.addWidget(self.pushButton_17)
        self.pushButton_27 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_27.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_27.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_5.addWidget(self.pushButton_27)
        self.pushButton_26 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_26.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_26.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_5.addWidget(self.pushButton_26)
        self.pushButton_25 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_25.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_25.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_5.addWidget(self.pushButton_25)
        self.pushButton_24 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_24.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_24.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_5.addWidget(self.pushButton_24)
        self.pushButton_23 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_23.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_23.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_5.addWidget(self.pushButton_23)
        self.pushButton_22 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_22.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_22.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_5.addWidget(self.pushButton_22)
        self.pushButton_21 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_21.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_21.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_5.addWidget(self.pushButton_21)
        self.pushButton_20 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_20.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_20.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_5.addWidget(self.pushButton_20)
        self.pushButton_19 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_19.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_19.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_5.addWidget(self.pushButton_19)
        self.pushButton_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_18.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_18.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_5.addWidget(self.pushButton_18)
        self.pushButton_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_15.setMinimumSize(QtCore.QSize(61, 31))
        self.pushButton_15.setMaximumSize(QtCore.QSize(61, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_5.addWidget(self.pushButton_15)
        self.scrollArea_groups.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_groups)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_zhangsan.setText(_translate("Form", "张三"))
        self.pushButton_lisi.setText(_translate("Form", "李四"))
        self.pushButton_3.setText(_translate("Form", "二狗"))
        self.pushButton_11.setText(_translate("Form", "麻花"))
        self.pushButton_10.setText(_translate("Form", "雀斑"))
        self.pushButton_7.setText(_translate("Form", "草灵"))
        self.pushButton_8.setText(_translate("Form", "马达"))
        self.pushButton_5.setText(_translate("Form", "思聪"))
        self.pushButton_6.setText(_translate("Form", "张三"))
        self.pushButton_9.setText(_translate("Form", "张三"))
        self.pushButton_4.setText(_translate("Form", "张三"))
        self.textEdit_chat.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_SendMessageInterface.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.pushButton_SendMessageInterface.setText(_translate("Form", "发送"))
        self.pushButton_addgroup.setText(_translate("Form", "加群"))
        self.pushButton_12.setText(_translate("Form", "群聊一"))
        self.pushButton_13.setText(_translate("Form", "群聊二"))
        self.pushButton_30.setText(_translate("Form", "群聊三"))
        self.pushButton_31.setText(_translate("Form", "群聊四"))
        self.pushButton_29.setText(_translate("Form", "群聊五"))
        self.pushButton_28.setText(_translate("Form", "群聊六"))
        self.pushButton_14.setText(_translate("Form", "群聊七"))
        self.pushButton_16.setText(_translate("Form", "张三"))
        self.pushButton_17.setText(_translate("Form", "张三"))
        self.pushButton_27.setText(_translate("Form", "张三"))
        self.pushButton_26.setText(_translate("Form", "张三"))
        self.pushButton_25.setText(_translate("Form", "张三"))
        self.pushButton_24.setText(_translate("Form", "张三"))
        self.pushButton_23.setText(_translate("Form", "张三"))
        self.pushButton_22.setText(_translate("Form", "张三"))
        self.pushButton_21.setText(_translate("Form", "张三"))
        self.pushButton_20.setText(_translate("Form", "张三"))
        self.pushButton_19.setText(_translate("Form", "张三"))
        self.pushButton_18.setText(_translate("Form", "张三"))
        self.pushButton_15.setText(_translate("Form", "张三"))

