# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(242, 167)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 54, 222, 66))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 2, 2)
        self.line_account = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_account.setObjectName("line_account")
        self.gridLayout.addWidget(self.line_account, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.line_passwd = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_passwd.setObjectName("line_passwd")
        self.gridLayout.addWidget(self.line_passwd, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.line_confirmpasswd = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_confirmpasswd.setText("")
        self.line_confirmpasswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_confirmpasswd.setObjectName("line_confirmpasswd")
        self.gridLayout.addWidget(self.line_confirmpasswd, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, 20, 171, 22))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(28, 130, 170, 19))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_signup = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_signup.setObjectName("pushButton_signup")
        self.horizontalLayout.addWidget(self.pushButton_signup)
        spacerItem3 = QtWidgets.QSpacerItem(48, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_cancle = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_cancle.setObjectName("pushButton_cancle")
        self.horizontalLayout.addWidget(self.pushButton_cancle)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "用户名"))
        self.line_account.setPlaceholderText(_translate("Form", "请输入你的账号用户名"))
        self.label_3.setText(_translate("Form", "输入密码     "))
        self.line_passwd.setPlaceholderText(_translate("Form", "请输入你的密码"))
        self.label_4.setText(_translate("Form", "确定密码"))
        self.line_confirmpasswd.setPlaceholderText(_translate("Form", "再次确定你的密码"))
        self.label.setText(_translate("Form", "                    注   册"))
        self.pushButton_signup.setText(_translate("Form", "注册"))
        self.pushButton_cancle.setText(_translate("Form", "取消"))

